const std = @import("std");
const alea = @import("alea");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    var stdout_buffer: [4096]u8 = undefined;
    var stdout_file = std.Io.File.stdout().writer(io, &stdout_buffer);
    const stdout = &stdout_file.interface;

    var seed = alea.Seed.fromString("alea-demo");
    var engine = alea.DefaultPrng.init(seed.stream(0).state);
    const rng = alea.Rng.init(&engine);

    var dice: [8]u8 = undefined;
    for (&dice) |*die| {
        die.* = rng.intRangeAtMost(u8, 1, 6);
    }

    const normal = rng.normal(f64, 10.0, 2.5);
    const outage_count = alea.distributions.binomial(rng, 40, 0.25);
    const weighted = rng.weightedIndex(&.{ 0.1, 0.2, 0.7 }).?;
    const token = try alea.ascii.Alphanumeric.alloc(init.gpa, rng, 16);
    defer init.gpa.free(token);
    const unicode = try alea.ascii.unicodeUtf8Alloc(init.gpa, rng, 6);
    defer init.gpa.free(unicode);
    const random_bytes = try rng.bytesAlloc(init.gpa, 8);
    defer init.gpa.free(random_bytes);
    const raw64 = rng.nextU64();
    const raw32 = rng.nextU32();
    var raw_fill_bytes: [8]u8 = undefined;
    rng.fillBytes(&raw_fill_bytes);
    var reader_buffer: [16]u8 = undefined;
    var rng_reader = rng.reader(&reader_buffer);
    var reader_bytes: [12]u8 = undefined;
    try rng_reader.readAll(&reader_bytes);
    var step_rng = alea.stepRng(255, 1);
    var step_bytes: [16]u8 = undefined;
    step_rng.fillBytes(&step_bytes);
    var constant_rng = alea.constRng(42);
    const constant_rng_next = constant_rng.nextU64();
    const random_value = rng.randomValue(u16);
    const random_words = try rng.valueBatch(u16, init.gpa, 4);
    defer init.gpa.free(random_words);
    const bounded_words = try rng.uintLessThanBatch(u16, init.gpa, 4, 1000);
    defer init.gpa.free(bounded_words);
    const inclusive_words = try rng.uintAtMostBatch(u16, init.gpa, 4, 999);
    defer init.gpa.free(inclusive_words);
    const random_bool = rng.randomBool(0.25);
    const random_ratio = rng.randomRatio(3, 8);
    const root_random_value = try alea.random(u16, io);
    const root_random_range = try alea.randomRange(u8, io, 1, 7);
    const root_random_bool = try alea.randomBool(io, 0.25);
    var root_random_bytes: [4]u8 = undefined;
    try alea.fill(u8, io, &root_random_bytes);
    var root_random_range_values: [4]u8 = undefined;
    try alea.fillRange(u8, io, &root_random_range_values, 1, 7);
    var root_random_inclusive_values: [4]u8 = undefined;
    try alea.fillRangeAtMost(u8, io, &root_random_inclusive_values, 1, 6);
    var root_random_bools: [8]bool = undefined;
    try alea.fillRandomBool(io, &root_random_bools, 0.25);
    var root_random_ratios: [8]bool = undefined;
    try alea.fillRandomRatio(io, &root_random_ratios, 3, 8);
    const root_random_value_batch = try alea.valueBatch(u16, io, init.gpa, 4);
    defer init.gpa.free(root_random_value_batch);
    const root_random_range_batch = try alea.rangeBatch(u8, io, init.gpa, 4, 1, 7);
    defer init.gpa.free(root_random_range_batch);
    const root_random_bool_batch = try alea.randomBoolBatch(io, init.gpa, 4, 0.25);
    defer init.gpa.free(root_random_bool_batch);
    const root_random_ratio_batch = try alea.randomRatioBatch(io, init.gpa, 4, 3, 8);
    defer init.gpa.free(root_random_ratio_batch);
    var root_open_values: [4]f32 = undefined;
    try alea.fillOpen(f32, io, &root_open_values);
    const root_open_batch = try alea.openBatch(f64, io, init.gpa, 4);
    defer init.gpa.free(root_open_batch);
    var root_open_closed_values: [4]f32 = undefined;
    try alea.fillOpenClosed(f32, io, &root_open_closed_values);
    const root_open_closed_batch = try alea.openClosedBatch(f64, io, init.gpa, 4);
    defer init.gpa.free(root_open_closed_batch);
    const root_duration_min: std.Io.Duration = .{ .nanoseconds = 10 * std.time.ns_per_ms };
    const root_duration_max: std.Io.Duration = .{ .nanoseconds = 20 * std.time.ns_per_ms };
    const root_duration_less_than = try alea.durationRangeLessThan(io, root_duration_min, root_duration_max);
    const root_duration_at_most = try alea.durationRangeAtMost(io, root_duration_min, root_duration_max);
    const root_duration_less_than_batch = try alea.durationRangeLessThanBatch(io, init.gpa, 3, root_duration_min, root_duration_max);
    defer init.gpa.free(root_duration_less_than_batch);
    const root_duration_at_most_batch = try alea.durationRangeAtMostBatch(io, init.gpa, 3, root_duration_min, root_duration_max);
    defer init.gpa.free(root_duration_at_most_batch);
    const root_char = try alea.char(io);
    const root_string = try alea.string(init.gpa, io, 8);
    defer init.gpa.free(root_string);
    const root_sample_string = try alea.sampleString(init.gpa, io, 8);
    defer init.gpa.free(root_sample_string);
    var root_append_buffer = try std.ArrayList(u8).initCapacity(init.gpa, 16);
    defer root_append_buffer.deinit(init.gpa);
    try alea.appendString(init.gpa, io, &root_append_buffer, 8);
    const root_unicode_scalar = try alea.unicodeScalar(io);
    var root_unicode_buffer: [16]u8 = undefined;
    const root_unicode_into = try alea.unicodeUtf8Into(io, &root_unicode_buffer, 4);
    const root_unicode_alloc = try alea.unicodeUtf8Alloc(init.gpa, io, 4);
    defer init.gpa.free(root_unicode_alloc);
    var root_random_iter = try alea.randomIter(u8, io);
    const root_random_iter_hint = root_random_iter.sizeHint();
    const root_random_iter_next = root_random_iter.next().?;
    const chance_flags = try rng.chanceBatch(init.gpa, 8, 0.25);
    defer init.gpa.free(chance_flags);
    const ratio_flags = try rng.ratioBatch(init.gpa, 8, 3, 8);
    defer init.gpa.free(ratio_flags);
    const vector_chance_flags = try rng.vectorChanceBatch(@Vector(8, bool), init.gpa, 2, 0.25);
    defer init.gpa.free(vector_chance_flags);
    const vector_ratio_flags = try rng.vectorRatioBatch(@Vector(8, bool), init.gpa, 2, 3, 8);
    defer init.gpa.free(vector_ratio_flags);
    const standard_normal_batch = try rng.standardNormalBatch(f64, init.gpa, 4);
    defer init.gpa.free(standard_normal_batch);
    const standard_exponential_batch = try rng.standardExponentialBatch(f64, init.gpa, 4);
    defer init.gpa.free(standard_exponential_batch);
    const normal_batch = try rng.normalBatch(f64, init.gpa, 4, 10, 2.5);
    defer init.gpa.free(normal_batch);
    const exponential_batch = try rng.exponentialBatch(f64, init.gpa, 4, 4);
    defer init.gpa.free(exponential_batch);
    const vector_standard_normal_batch = try rng.vectorStandardNormalBatch(@Vector(4, f64), init.gpa, 2);
    defer init.gpa.free(vector_standard_normal_batch);
    const vector_standard_exponential_batch = try rng.vectorStandardExponentialBatch(@Vector(4, f64), init.gpa, 2);
    defer init.gpa.free(vector_standard_exponential_batch);
    const vector_normal_batch = try rng.vectorNormalBatch(@Vector(4, f64), init.gpa, 2, 0, 1);
    defer init.gpa.free(vector_normal_batch);
    const vector_exponential_batch = try rng.vectorExponentialBatch(@Vector(4, f64), init.gpa, 2, 2);
    defer init.gpa.free(vector_exponential_batch);

    const dirichlet = try alea.distributions.Dirichlet(f64).init(&.{ 1.0, 2.0, 3.0 });
    var proportions: [3]f64 = undefined;
    dirichlet.sampleInto(rng, &proportions);

    var deck = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8 };
    const hand = alea.seq.partialShuffle(rng, u8, &deck, 3);
    const colors = [_][]const u8{ "red", "green", "blue", "gold" };
    var mutable_colors = colors;
    const color_index = rng.chooseIndex(colors.len).?;
    const compact_color_index = rng.chooseIndexU32(@intCast(colors.len)).?;
    const color_index_array = rng.chooseIndexArray(4, colors.len).?;
    const compact_color_index_array = try rng.chooseIndexArrayU32Checked(4, @intCast(colors.len));
    const color_indices = try rng.chooseIndexBatch(init.gpa, 4, colors.len);
    defer init.gpa.free(color_indices);
    const compact_color_indices = try rng.chooseIndexU32Batch(init.gpa, 4, @intCast(colors.len));
    defer init.gpa.free(compact_color_indices);
    const color_value_array = rng.chooseValueArray([]const u8, 4, &colors).?;
    const color_values = try rng.chooseBatch([]const u8, init.gpa, 4, &colors);
    defer init.gpa.free(color_values);
    const color_ptr = rng.chooseConstPtr([]const u8, &colors).?;
    const color_ptr_array = rng.chooseConstPtrArray([]const u8, 4, &colors).?;
    const color_ptrs = try rng.chooseConstPtrBatch([]const u8, init.gpa, 4, &colors);
    defer init.gpa.free(color_ptrs);
    const mutable_color_ptr_array = rng.choosePtrArray([]const u8, 4, &mutable_colors).?;
    const mutable_color_ptrs = try rng.choosePtrBatch([]const u8, init.gpa, 4, &mutable_colors);
    defer init.gpa.free(mutable_color_ptrs);
    const die_sampler = try alea.distributions.Uniform(u8).initInclusive(1, 6);
    const sample_roll = rng.sample(u8, die_sampler);
    const owned_rolls = try rng.sampleBatch(u8, init.gpa, die_sampler, 6);
    defer init.gpa.free(owned_rolls);

    const Iter = struct {
        next_value: u8 = 0,
        pub fn next(self: *@This()) ?u8 {
            if (self.next_value == 10) return null;
            const value = self.next_value;
            self.next_value += 1;
            return value;
        }
    };
    var iter = Iter{};
    const stream_choice = alea.seq.chooseIterator(rng, u8, &iter).?;
    var die_iter = rng.sampleIter(u8, die_sampler);
    const die_iter_hint = die_iter.sizeHint();
    const die_iter_roll = die_iter.next().?;

    seed = seed.mix("child-stream");
    var child_engine = alea.FastPrng.init(seed.stream(42).state);
    const child_rng = alea.Rng.init(&child_engine);

    try stdout.print("dice: {any}\n", .{dice});
    try stdout.print("normal(mean=10,stddev=2.5): {d:.4}\n", .{normal});
    try stdout.print("binomial(n=40,p=.25): {}\n", .{outage_count});
    try stdout.print("weighted index: {}\n", .{weighted});
    try stdout.print("token: {s}\n", .{token});
    try stdout.print("unicode scalars: {s}\n", .{unicode});
    try stdout.print("bytesAlloc: {any}\n", .{random_bytes});
    try stdout.print("nextU64 raw: {}, nextU32 raw: {}\n", .{ raw64, raw32 });
    try stdout.print("fillBytes raw: {any}\n", .{raw_fill_bytes});
    try stdout.print("rngReader bytes: {any}\n", .{reader_bytes});
    try stdout.print("StepRng bytes: {any}, constRng next: {}\n", .{ step_bytes, constant_rng_next });
    try stdout.print("randomValue u16: {}\n", .{random_value});
    try stdout.print("valueBatch u16: {any}\n", .{random_words});
    try stdout.print("uintLessThanBatch u16 <1000: {any}\n", .{bounded_words});
    try stdout.print("uintAtMostBatch u16 <=999: {any}\n", .{inclusive_words});
    try stdout.print("randomBool p=.25: {}, randomRatio 3/8: {}\n", .{ random_bool, random_ratio });
    try stdout.print("root random helpers: random={}, range={}, bool={}, fill={any}, rangeFill={any}, inclusiveFill={any}, boolFill={any}, ratioFill={any}, valueBatch={any}, rangeBatch={any}, boolBatch={any}, ratioBatch={any}, iterNext={}, iterUnbounded={}\n", .{ root_random_value, root_random_range, root_random_bool, root_random_bytes, root_random_range_values, root_random_inclusive_values, root_random_bools, root_random_ratios, root_random_value_batch, root_random_range_batch, root_random_bool_batch, root_random_ratio_batch, root_random_iter_next, root_random_iter_hint.upper == null });
    try stdout.print("root endpoint float helpers: openFill={any}, openBatch={any}, openClosedFill={any}, openClosedBatch={any}\n", .{ root_open_values, root_open_batch, root_open_closed_values, root_open_closed_batch });
    try stdout.print("root duration helpers: lessThan={}ns, atMost={}ns, lessThanBatch={any}, atMostBatch={any}\n", .{ root_duration_less_than.nanoseconds, root_duration_at_most.nanoseconds, root_duration_less_than_batch, root_duration_at_most_batch });
    try stdout.print("root string helpers: char={c}, string={s}, sampleString={s}, appendString={s}, unicodeScalar=U+{X}, unicodeInto={s}, unicodeAlloc={s}\n", .{ root_char, root_string, root_sample_string, root_append_buffer.items, root_unicode_scalar, root_unicode_into, root_unicode_alloc });
    try stdout.print("chanceBatch p=.25: {any}\n", .{chance_flags});
    try stdout.print("ratioBatch 3/8: {any}\n", .{ratio_flags});
    try stdout.print("vectorChanceBatch boolx8 p=.25: {any}\n", .{vector_chance_flags});
    try stdout.print("vectorRatioBatch boolx8 3/8: {any}\n", .{vector_ratio_flags});
    try stdout.print("standardNormalBatch: {any}\n", .{standard_normal_batch});
    try stdout.print("standardExponentialBatch: {any}\n", .{standard_exponential_batch});
    try stdout.print("normalBatch: {any}\n", .{normal_batch});
    try stdout.print("exponentialBatch: {any}\n", .{exponential_batch});
    try stdout.print("vectorStandardNormalBatch f64x4: {any}\n", .{vector_standard_normal_batch});
    try stdout.print("vectorStandardExponentialBatch f64x4: {any}\n", .{vector_standard_exponential_batch});
    try stdout.print("vectorNormalBatch f64x4: {any}\n", .{vector_normal_batch});
    try stdout.print("vectorExponentialBatch f64x4: {any}\n", .{vector_exponential_batch});
    try stdout.print("dirichlet: {any}\n", .{proportions});
    try stdout.print("partial shuffle hand: {any}\n", .{hand});
    try stdout.print("index choice: {} ({s})\n", .{ color_index, colors[color_index] });
    try stdout.print("u32 index choice: {} ({s})\n", .{ compact_color_index, colors[compact_color_index] });
    try stdout.print("index choice array: {any}\n", .{color_index_array});
    try stdout.print("u32 index choice array: {any}\n", .{compact_color_index_array});
    try stdout.print("index choice batch: {any}\n", .{color_indices});
    try stdout.print("u32 index choice batch: {any}\n", .{compact_color_indices});
    try stdout.print("value choice array: {s}, {s}, {s}, {s}\n", .{ color_value_array[0], color_value_array[1], color_value_array[2], color_value_array[3] });
    try stdout.print("value choice batch: {s}, {s}, {s}, {s}\n", .{ color_values[0], color_values[1], color_values[2], color_values[3] });
    try stdout.print("const pointer choice: {s}\n", .{color_ptr.*});
    try stdout.print("const pointer choice array: {s}, {s}, {s}, {s}\n", .{ color_ptr_array[0].*, color_ptr_array[1].*, color_ptr_array[2].*, color_ptr_array[3].* });
    try stdout.print("const pointer choice batch: {s}, {s}, {s}, {s}\n", .{ color_ptrs[0].*, color_ptrs[1].*, color_ptrs[2].*, color_ptrs[3].* });
    try stdout.print("mutable pointer choice array: {s}, {s}, {s}, {s}\n", .{ mutable_color_ptr_array[0].*, mutable_color_ptr_array[1].*, mutable_color_ptr_array[2].*, mutable_color_ptr_array[3].* });
    try stdout.print("mutable pointer choice batch: {s}, {s}, {s}, {s}\n", .{ mutable_color_ptrs[0].*, mutable_color_ptrs[1].*, mutable_color_ptrs[2].*, mutable_color_ptrs[3].* });
    try stdout.print("sample die: {}\n", .{sample_roll});
    try stdout.print("sampleBatch dice: {any}\n", .{owned_rolls});
    try stdout.print("iterator choice: {}\n", .{stream_choice});
    try stdout.print("sampleIter sizeHint: {}..unbounded={}, next={}\n", .{ die_iter_hint.lower, die_iter_hint.upper == null, die_iter_roll });
    try stdout.print("child stream u64: {}\n", .{child_rng.next()});
    try stdout.flush();
}
