const std = @import("std");
const alea = @import("alea");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    var stdout_buffer: [4096]u8 = undefined;
    var stdout_file = std.Io.File.stdout().writer(io, &stdout_buffer);
    const stdout = &stdout_file.interface;

    var seed = alea.Seed.fromString("alea-demo");
    var engine = alea.DefaultPrng.init(seed.stream(0).state);
    const rng = alea.Rng.init(&engine);

    var dice: [8]u8 = undefined;
    for (&dice) |*die| {
        die.* = rng.intRangeAtMost(u8, 1, 6);
    }

    const normal = rng.normal(f64, 10.0, 2.5);
    const outage_count = alea.distributions.binomial(rng, 40, 0.25);
    const weighted = rng.weightedIndex(&.{ 0.1, 0.2, 0.7 }).?;
    const token = try alea.ascii.Alphanumeric.alloc(init.gpa, rng, 16);
    defer init.gpa.free(token);
    const unicode = try alea.ascii.unicodeUtf8Alloc(init.gpa, rng, 6);
    defer init.gpa.free(unicode);
    const random_bytes = try rng.bytesAlloc(init.gpa, 8);
    defer init.gpa.free(random_bytes);
    const raw64 = rng.nextU64();
    const raw32 = rng.nextU32();
    var raw_fill_bytes: [8]u8 = undefined;
    rng.fillBytes(&raw_fill_bytes);
    var reader_buffer: [16]u8 = undefined;
    var rng_reader = rng.reader(&reader_buffer);
    var reader_bytes: [12]u8 = undefined;
    try rng_reader.readAll(&reader_bytes);
    var step_rng = alea.stepRng(255, 1);
    var step_bytes: [16]u8 = undefined;
    step_rng.fillBytes(&step_bytes);
    var constant_rng = alea.constRng(42);
    const constant_rng_next = constant_rng.nextU64();
    const random_value = rng.randomValue(u16);
    const random_words = try rng.valueBatch(u16, init.gpa, 4);
    defer init.gpa.free(random_words);
    const bounded_words = try rng.uintLessThanBatch(u16, init.gpa, 4, 1000);
    defer init.gpa.free(bounded_words);
    const inclusive_words = try rng.uintAtMostBatch(u16, init.gpa, 4, 999);
    defer init.gpa.free(inclusive_words);
    const random_bool = rng.randomBool(0.25);
    const random_ratio = rng.randomRatio(3, 8);
    const root_random_value = try alea.random(u16, io);
    const root_random_range = try alea.randomRange(u8, io, 1, 7);
    const root_random_bool = try alea.randomBool(io, 0.25);
    const root_die_sampler = try alea.distributions.Uniform(u8).initInclusive(1, 6);
    const root_sample_die = try alea.sample(u8, io, root_die_sampler);
    var root_sample_dice_fill: [4]u8 = undefined;
    try alea.fillSample(u8, io, &root_sample_dice_fill, root_die_sampler);
    const root_sample_dice_batch = try alea.sampleBatch(u8, io, init.gpa, root_die_sampler, 4);
    defer init.gpa.free(root_sample_dice_batch);
    const root_colors = [_][]const u8{ "red", "green", "blue", "gold" };
    const root_choice_index = (try alea.chooseIndex(io, root_colors.len)).?;
    const root_choice_index_u32 = (try alea.chooseIndexU32(io, @intCast(root_colors.len))).?;
    var root_choice_indices: [4]usize = undefined;
    try alea.fillChooseIndex(io, &root_choice_indices, root_colors.len);
    var root_choice_indices_u32: [4]u32 = undefined;
    try alea.fillChooseIndexU32(io, &root_choice_indices_u32, @intCast(root_colors.len));
    const root_choice_index_array = (try alea.chooseIndexArray(io, 4, root_colors.len)).?;
    const root_choice_index_array_u32 = (try alea.chooseIndexArrayU32(io, 4, @intCast(root_colors.len))).?;
    const root_choice_value_array = (try alea.chooseValueArray([]const u8, io, 4, &root_colors)).?;
    const root_choice_repeated_value_array = (try alea.chooseRepeatedValueArray([]const u8, io, 4, &root_colors)).?;
    const root_choice_ptr = (try alea.chooseConstPtr([]const u8, io, &root_colors)).?;
    const root_choice_ptr_array = (try alea.chooseConstPtrArray([]const u8, io, 4, &root_colors)).?;
    const root_choice_repeated_ptr_array = (try alea.chooseRepeatedConstPtrArray([]const u8, io, 4, &root_colors)).?;
    var root_mutable_colors = root_colors;
    const root_choice_mut_ptr = (try alea.choosePtr([]const u8, io, &root_mutable_colors)).?;
    const root_choice_mut_ptr_array = (try alea.choosePtrArray([]const u8, io, 4, &root_mutable_colors)).?;
    const root_choice_repeated_mut_ptr_array = (try alea.chooseRepeatedPtrArray([]const u8, io, 4, &root_mutable_colors)).?;
    const root_choice_batch = try alea.chooseBatch([]const u8, io, init.gpa, 4, &root_colors);
    defer init.gpa.free(root_choice_batch);
    const root_choice_ptr_batch = try alea.chooseConstPtrBatch([]const u8, io, init.gpa, 4, &root_colors);
    defer init.gpa.free(root_choice_ptr_batch);
    const root_choice_mut_ptr_batch = try alea.choosePtrBatch([]const u8, io, init.gpa, 4, &root_mutable_colors);
    defer init.gpa.free(root_choice_mut_ptr_batch);
    var root_shuffle_deck = [_]u8{ 1, 2, 3, 4, 5, 6 };
    try alea.shuffle(u8, io, &root_shuffle_deck);
    var root_partial_deck = [_]u8{ 1, 2, 3, 4, 5, 6 };
    const root_partial_hand = try alea.partialShuffle(u8, io, &root_partial_deck, 3);
    var root_tail_deck = [_]u8{ 1, 2, 3, 4, 5, 6 };
    const root_tail_hand = try alea.partialShuffleTail(u8, io, &root_tail_deck, 3);
    const root_no_replacement = try alea.sampleWithoutReplacement(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_no_replacement);
    const root_no_replacement_array = (try alea.sampleItemsArray(u8, io, 3, &root_shuffle_deck)).?;
    const root_no_replacement_choose_array = (try alea.chooseArray(u8, io, 3, &root_shuffle_deck)).?;
    const root_no_replacement_ptr_array = (try alea.samplePtrArray(u8, io, 3, &root_shuffle_deck)).?;
    const root_no_replacement_ptrs = try alea.samplePtrs(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_no_replacement_ptrs);
    const root_no_replacement_mut_ptr_array = (try alea.sampleMutPtrArray(u8, io, 3, &root_shuffle_deck)).?;
    const root_no_replacement_mut_ptrs = try alea.sampleMutPtrs(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_no_replacement_mut_ptrs);
    var root_no_replacement_items_into: [3]u8 = undefined;
    var root_no_replacement_items_indices: [3]usize = undefined;
    _ = try alea.sampleItemsInto(u8, io, &root_shuffle_deck, &root_no_replacement_items_into, &root_no_replacement_items_indices);
    var root_no_replacement_ptrs_into: [3]*const u8 = undefined;
    var root_no_replacement_ptr_indices: [3]usize = undefined;
    _ = try alea.samplePtrsInto(u8, io, &root_shuffle_deck, &root_no_replacement_ptrs_into, &root_no_replacement_ptr_indices);
    var root_no_replacement_mut_ptrs_into: [3]*u8 = undefined;
    var root_no_replacement_mut_ptr_indices: [3]usize = undefined;
    _ = try alea.sampleMutPtrsInto(u8, io, &root_shuffle_deck, &root_no_replacement_mut_ptrs_into, &root_no_replacement_mut_ptr_indices);
    const root_choose_multiple = try alea.chooseMultiple(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_choose_multiple);
    const root_choose_multiple_ptrs = try alea.chooseMultiplePtrs(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_choose_multiple_ptrs);
    const root_choose_multiple_mut_ptrs = try alea.chooseMultipleMutPtrs(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_choose_multiple_mut_ptrs);
    var root_choose_multiple_into: [3]u8 = undefined;
    var root_choose_multiple_indices: [3]usize = undefined;
    _ = try alea.chooseMultipleInto(u8, io, &root_shuffle_deck, &root_choose_multiple_into, &root_choose_multiple_indices);
    var root_choose_multiple_ptrs_into: [3]*const u8 = undefined;
    var root_choose_multiple_ptr_indices: [3]usize = undefined;
    _ = try alea.chooseMultiplePtrsInto(u8, io, &root_shuffle_deck, &root_choose_multiple_ptrs_into, &root_choose_multiple_ptr_indices);
    var root_choose_multiple_mut_ptrs_into: [3]*u8 = undefined;
    var root_choose_multiple_mut_ptr_indices: [3]usize = undefined;
    _ = try alea.chooseMultipleMutPtrsInto(u8, io, &root_shuffle_deck, &root_choose_multiple_mut_ptrs_into, &root_choose_multiple_mut_ptr_indices);
    var root_sample_items_iter = try alea.sampleItemsIter(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer root_sample_items_iter.deinit();
    var root_sample_items_iter_values: [3]u8 = undefined;
    _ = root_sample_items_iter.fill(&root_sample_items_iter_values);
    var root_sample_ptrs_iter = try alea.samplePtrsIter(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer root_sample_ptrs_iter.deinit();
    var root_sample_ptrs_iter_values: [3]*const u8 = undefined;
    _ = root_sample_ptrs_iter.fill(&root_sample_ptrs_iter_values);
    var root_sample_mut_ptrs_iter = try alea.sampleMutPtrsIter(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer root_sample_mut_ptrs_iter.deinit();
    var root_sample_mut_ptrs_iter_values: [3]*u8 = undefined;
    _ = root_sample_mut_ptrs_iter.fill(&root_sample_mut_ptrs_iter_values);
    const root_reservoir = try alea.reservoirSample(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_reservoir);
    const root_reservoir_ptrs = try alea.reservoirSamplePtrs(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_reservoir_ptrs);
    const root_reservoir_mut_ptrs = try alea.reservoirSampleMutPtrs(u8, io, init.gpa, &root_shuffle_deck, 3);
    defer init.gpa.free(root_reservoir_mut_ptrs);
    var root_reservoir_into: [3]u8 = undefined;
    try alea.reservoirSampleInto(u8, io, &root_shuffle_deck, &root_reservoir_into);
    var root_reservoir_ptrs_into: [3]*const u8 = undefined;
    try alea.reservoirSamplePtrsInto(u8, io, &root_shuffle_deck, &root_reservoir_ptrs_into);
    var root_reservoir_mut_ptrs_into: [3]*u8 = undefined;
    try alea.reservoirSampleMutPtrsInto(u8, io, &root_shuffle_deck, &root_reservoir_mut_ptrs_into);
    const root_sample_indices = try alea.sampleIndices(io, init.gpa, root_shuffle_deck.len, 3);
    defer init.gpa.free(root_sample_indices);
    const root_sample_index_vec = try alea.sampleIndexVec(io, init.gpa, root_shuffle_deck.len, 3);
    defer root_sample_index_vec.deinit(init.gpa);
    var root_sample_index_vec_values: [3]usize = undefined;
    try root_sample_index_vec.copyInto(&root_sample_index_vec_values);
    const root_sample_index_array = (try alea.sampleArray(io, 3, root_shuffle_deck.len)).?;
    const root_sample_index_array_u32 = (try alea.sampleArrayU32(io, 3, @intCast(root_shuffle_deck.len))).?;
    var root_sample_indices_into: [3]usize = undefined;
    try alea.sampleIndicesInto(io, root_shuffle_deck.len, &root_sample_indices_into);
    const root_sample_indices_u32 = try alea.sampleIndicesU32(io, init.gpa, @intCast(root_shuffle_deck.len), 3);
    defer init.gpa.free(root_sample_indices_u32);
    const root_weights = [_]f64{ 0.1, 0.2, 0.7 };
    const root_weighted_items = root_colors[0..3];
    const root_sample_weighted_indices = try alea.sampleWeightedIndices(f64, io, init.gpa, &root_weights, 2);
    defer init.gpa.free(root_sample_weighted_indices);
    const root_sample_weighted_index_vec = try alea.sampleWeightedIndexVec(f64, io, init.gpa, &root_weights, 2);
    defer root_sample_weighted_index_vec.deinit(init.gpa);
    var root_sample_weighted_index_vec_values: [2]usize = undefined;
    try root_sample_weighted_index_vec.copyInto(&root_sample_weighted_index_vec_values);
    const root_sample_weighted_index_array = (try alea.sampleWeightedIndexArray(f64, io, 2, &root_weights)).?;
    const root_sample_weighted_index_array_u32 = (try alea.sampleWeightedIndexArrayU32(f64, io, 2, &root_weights)).?;
    var root_sample_weighted_indices_into: [2]usize = undefined;
    var root_sample_weighted_keys: [2]f64 = undefined;
    _ = try alea.sampleWeightedIndicesInto(f64, io, &root_weights, &root_sample_weighted_indices_into, &root_sample_weighted_keys);
    var root_sample_weighted_indices_u32_into: [2]u32 = undefined;
    var root_sample_weighted_u32_keys: [2]f64 = undefined;
    _ = try alea.sampleWeightedIndicesU32Into(f64, io, &root_weights, &root_sample_weighted_indices_u32_into, &root_sample_weighted_u32_keys);
    const root_sample_weighted_values = try alea.sampleWeighted([]const u8, f64, io, init.gpa, root_weighted_items, &root_weights, 2);
    defer init.gpa.free(root_sample_weighted_values);
    var root_sample_weighted_values_into: [2][]const u8 = undefined;
    var root_sample_weighted_value_indices: [2]usize = undefined;
    var root_sample_weighted_value_keys: [2]f64 = undefined;
    _ = try alea.sampleWeightedInto([]const u8, f64, io, root_weighted_items, &root_weights, &root_sample_weighted_values_into, &root_sample_weighted_value_indices, &root_sample_weighted_value_keys);
    const root_sample_weighted_value_array = (try alea.sampleWeightedArray([]const u8, f64, io, 2, root_weighted_items, &root_weights)).?;
    const root_sample_weighted_ptrs = try alea.sampleWeightedPtrs([]const u8, f64, io, init.gpa, root_weighted_items, &root_weights, 2);
    defer init.gpa.free(root_sample_weighted_ptrs);
    var root_sample_weighted_ptrs_into: [2]*const []const u8 = undefined;
    var root_sample_weighted_ptr_indices: [2]usize = undefined;
    var root_sample_weighted_ptr_keys: [2]f64 = undefined;
    _ = try alea.sampleWeightedPtrsInto([]const u8, f64, io, root_weighted_items, &root_weights, &root_sample_weighted_ptrs_into, &root_sample_weighted_ptr_indices, &root_sample_weighted_ptr_keys);
    var root_sample_weighted_mut_items = root_weighted_items.*;
    var root_sample_weighted_mut_ptrs_into: [2]*[]const u8 = undefined;
    var root_sample_weighted_mut_ptr_indices: [2]usize = undefined;
    var root_sample_weighted_mut_ptr_keys: [2]f64 = undefined;
    _ = try alea.sampleWeightedMutPtrsInto([]const u8, f64, io, &root_sample_weighted_mut_items, &root_weights, &root_sample_weighted_mut_ptrs_into, &root_sample_weighted_mut_ptr_indices, &root_sample_weighted_mut_ptr_keys);
    const root_sample_weighted_mut_ptrs = try alea.sampleWeightedMutPtrs([]const u8, f64, io, init.gpa, &root_sample_weighted_mut_items, &root_weights, 2);
    defer init.gpa.free(root_sample_weighted_mut_ptrs);
    const RootIter = struct {
        next_value: u8 = 0,
        pub fn next(self: *@This()) ?u8 {
            if (self.next_value == 10) return null;
            const value = self.next_value;
            self.next_value += 1;
            return value;
        }
    };
    var root_iter = RootIter{};
    const root_iterator_choice = (try alea.chooseIterator(u8, io, &root_iter)).?;
    const RootWeightedIter = struct {
        const Entry = struct { item: u8, weight: f64 };
        items: []const Entry,
        index: usize = 0,
        pub fn next(self: *@This()) ?Entry {
            if (self.index == self.items.len) return null;
            const value = self.items[self.index];
            self.index += 1;
            return value;
        }
    };
    const root_weighted_iter_entries = [_]RootWeightedIter.Entry{
        .{ .item = 10, .weight = 1 },
        .{ .item = 20, .weight = 2 },
        .{ .item = 30, .weight = 3 },
    };
    var root_weighted_iter = RootWeightedIter{ .items = &root_weighted_iter_entries };
    const root_weighted_iterator_choice = (try alea.chooseIteratorWeighted(u8, io, &root_weighted_iter)).?;
    var root_sample_iter = RootIter{};
    const root_iterator_sample = try alea.sampleIterator(u8, io, init.gpa, &root_sample_iter, 4);
    defer init.gpa.free(root_iterator_sample);
    var root_sample_iter_into_source = RootIter{};
    var root_iterator_sample_into: [4]u8 = undefined;
    _ = try alea.sampleIteratorInto(u8, io, &root_sample_iter_into_source, &root_iterator_sample_into);
    var root_sample_iter_fill_source = RootIter{};
    var root_iterator_sample_fill: [4]u8 = undefined;
    _ = try alea.sampleIteratorFill(u8, io, &root_sample_iter_fill_source, &root_iterator_sample_fill);
    var root_sample_iter_array_source = RootIter{};
    const root_iterator_sample_array = (try alea.sampleIteratorArray(u8, io, 4, &root_sample_iter_array_source)).?;
    var root_weighted_sample_iter = RootWeightedIter{ .items = &root_weighted_iter_entries };
    const root_weighted_iterator_sample = try alea.sampleIteratorWeighted(u8, io, init.gpa, &root_weighted_sample_iter, 2);
    defer init.gpa.free(root_weighted_iterator_sample);
    var root_weighted_sample_into_iter = RootWeightedIter{ .items = &root_weighted_iter_entries };
    var root_weighted_iterator_sample_into: [2]u8 = undefined;
    var root_weighted_iterator_sample_keys: [2]f64 = undefined;
    _ = try alea.sampleIteratorWeightedInto(u8, io, &root_weighted_sample_into_iter, &root_weighted_iterator_sample_into, &root_weighted_iterator_sample_keys);
    var root_weighted_sample_array_iter = RootWeightedIter{ .items = &root_weighted_iter_entries };
    const root_weighted_iterator_sample_array = (try alea.sampleIteratorWeightedArray(u8, io, 2, &root_weighted_sample_array_iter)).?;
    const root_weighted_index = (try alea.weightedIndex(io, &root_weights)).?;
    const root_weighted_index_u32 = (try alea.weightedIndexU32(io, &root_weights)).?;
    const RootIndexWeight = struct {
        fn weight(index: usize) f64 {
            return @floatFromInt(index + 1);
        }
    };
    const root_weighted_index_by_index = (try alea.weightedIndexByIndex(f64, io, root_weights.len, RootIndexWeight.weight)).?;
    const root_weighted_index_u32_by_index = (try alea.weightedIndexU32ByIndex(f64, io, root_weights.len, RootIndexWeight.weight)).?;
    var root_weighted_indices_by_index: [4]?usize = undefined;
    try alea.fillWeightedIndexByIndex(f64, io, &root_weighted_indices_by_index, root_weights.len, RootIndexWeight.weight);
    var root_weighted_indices_u32_by_index: [4]?u32 = undefined;
    try alea.fillWeightedIndexU32ByIndex(f64, io, &root_weighted_indices_u32_by_index, root_weights.len, RootIndexWeight.weight);
    var root_weighted_indices: [4]?usize = undefined;
    try alea.fillWeightedIndex(io, &root_weighted_indices, &root_weights);
    var root_weighted_indices_u32: [4]?u32 = undefined;
    try alea.fillWeightedIndexU32(io, &root_weighted_indices_u32, &root_weights);
    const root_weighted_index_array = (try alea.weightedIndexArray(io, 4, &root_weights)).?;
    const root_weighted_index_u32_array = (try alea.weightedIndexU32Array(io, 4, &root_weights)).?;
    const root_weighted_value = (try alea.chooseWeighted([]const u8, io, root_weighted_items, &root_weights)).?;
    var root_weighted_values: [4]?[]const u8 = undefined;
    try alea.fillChooseWeighted([]const u8, io, &root_weighted_values, root_weighted_items, &root_weights);
    const root_weighted_value_array = (try alea.chooseWeightedValueArray([]const u8, io, 4, root_weighted_items, &root_weights)).?;
    const root_weighted_ptr = (try alea.chooseWeightedConstPtr([]const u8, io, root_weighted_items, &root_weights)).?;
    const root_weighted_ptr_array_checked = try alea.chooseWeightedConstPtrArrayChecked([]const u8, io, 4, root_weighted_items, &root_weights);
    var root_weighted_mut_items = root_weighted_items.*;
    const root_weighted_mut_ptr = (try alea.chooseWeightedPtr([]const u8, io, &root_weighted_mut_items, &root_weights)).?;
    const root_weighted_mut_ptr_array_checked = try alea.chooseWeightedPtrArrayChecked([]const u8, io, 4, &root_weighted_mut_items, &root_weights);
    const root_weighted_index_batch = try alea.weightedIndexBatch(io, init.gpa, 4, &root_weights);
    defer init.gpa.free(root_weighted_index_batch);
    const root_weighted_index_u32_batch = try alea.weightedIndexU32Batch(io, init.gpa, 4, &root_weights);
    defer init.gpa.free(root_weighted_index_u32_batch);
    const root_weighted_value_batch = try alea.chooseWeightedBatch([]const u8, io, init.gpa, 4, root_weighted_items, &root_weights);
    defer init.gpa.free(root_weighted_value_batch);
    const root_weighted_ptr_batch_checked = try alea.chooseWeightedConstPtrBatchChecked([]const u8, io, init.gpa, 4, root_weighted_items, &root_weights);
    defer init.gpa.free(root_weighted_ptr_batch_checked);
    const root_weighted_mut_ptr_batch_checked = try alea.chooseWeightedPtrBatchChecked([]const u8, io, init.gpa, 4, &root_weighted_mut_items, &root_weights);
    defer init.gpa.free(root_weighted_mut_ptr_batch_checked);
    var root_random_bytes: [4]u8 = undefined;
    try alea.fill(u8, io, &root_random_bytes);
    var root_random_range_values: [4]u8 = undefined;
    try alea.fillRange(u8, io, &root_random_range_values, 1, 7);
    var root_random_inclusive_values: [4]u8 = undefined;
    try alea.fillRangeAtMost(u8, io, &root_random_inclusive_values, 1, 6);
    var root_random_bools: [8]bool = undefined;
    try alea.fillRandomBool(io, &root_random_bools, 0.25);
    var root_random_ratios: [8]bool = undefined;
    try alea.fillRandomRatio(io, &root_random_ratios, 3, 8);
    const root_random_value_batch = try alea.valueBatch(u16, io, init.gpa, 4);
    defer init.gpa.free(root_random_value_batch);
    const root_random_range_batch = try alea.rangeBatch(u8, io, init.gpa, 4, 1, 7);
    defer init.gpa.free(root_random_range_batch);
    const root_random_bool_batch = try alea.randomBoolBatch(io, init.gpa, 4, 0.25);
    defer init.gpa.free(root_random_bool_batch);
    const root_random_ratio_batch = try alea.randomRatioBatch(io, init.gpa, 4, 3, 8);
    defer init.gpa.free(root_random_ratio_batch);
    var root_open_values: [4]f32 = undefined;
    try alea.fillOpen(f32, io, &root_open_values);
    const root_open_batch = try alea.openBatch(f64, io, init.gpa, 4);
    defer init.gpa.free(root_open_batch);
    var root_open_closed_values: [4]f32 = undefined;
    try alea.fillOpenClosed(f32, io, &root_open_closed_values);
    const root_open_closed_batch = try alea.openClosedBatch(f64, io, init.gpa, 4);
    defer init.gpa.free(root_open_closed_batch);
    const root_duration_min: std.Io.Duration = .{ .nanoseconds = 10 * std.time.ns_per_ms };
    const root_duration_max: std.Io.Duration = .{ .nanoseconds = 20 * std.time.ns_per_ms };
    const root_duration_less_than = try alea.durationRangeLessThan(io, root_duration_min, root_duration_max);
    const root_duration_at_most = try alea.durationRangeAtMost(io, root_duration_min, root_duration_max);
    const root_duration_less_than_batch = try alea.durationRangeLessThanBatch(io, init.gpa, 3, root_duration_min, root_duration_max);
    defer init.gpa.free(root_duration_less_than_batch);
    const root_duration_at_most_batch = try alea.durationRangeAtMostBatch(io, init.gpa, 3, root_duration_min, root_duration_max);
    defer init.gpa.free(root_duration_at_most_batch);
    const root_char = try alea.char(io);
    const root_string = try alea.string(init.gpa, io, 8);
    defer init.gpa.free(root_string);
    const root_sample_string = try alea.sampleString(init.gpa, io, 8);
    defer init.gpa.free(root_sample_string);
    var root_append_buffer = try std.ArrayList(u8).initCapacity(init.gpa, 16);
    defer root_append_buffer.deinit(init.gpa);
    try alea.appendString(init.gpa, io, &root_append_buffer, 8);
    const root_unicode_scalar = try alea.unicodeScalar(io);
    var root_unicode_scalar_fill: [4]u21 = undefined;
    try alea.fillUnicodeScalarRangeAtMost(io, &root_unicode_scalar_fill, 0x41, 0x5A);
    const root_unicode_scalar_batch = try alea.unicodeScalarRangeAtMostBatch(io, init.gpa, 4, 0x41, 0x5A);
    defer init.gpa.free(root_unicode_scalar_batch);
    var root_unicode_buffer: [16]u8 = undefined;
    const root_unicode_into = try alea.unicodeUtf8Into(io, &root_unicode_buffer, 4);
    const root_unicode_alloc = try alea.unicodeUtf8Alloc(init.gpa, io, 4);
    defer init.gpa.free(root_unicode_alloc);
    var root_random_iter = try alea.randomIter(u8, io);
    const root_random_iter_hint = root_random_iter.sizeHint();
    const root_random_iter_next = root_random_iter.next().?;
    const chance_flags = try rng.chanceBatch(init.gpa, 8, 0.25);
    defer init.gpa.free(chance_flags);
    const ratio_flags = try rng.ratioBatch(init.gpa, 8, 3, 8);
    defer init.gpa.free(ratio_flags);
    const vector_chance_flags = try rng.vectorChanceBatch(@Vector(8, bool), init.gpa, 2, 0.25);
    defer init.gpa.free(vector_chance_flags);
    const vector_ratio_flags = try rng.vectorRatioBatch(@Vector(8, bool), init.gpa, 2, 3, 8);
    defer init.gpa.free(vector_ratio_flags);
    const standard_normal_batch = try rng.standardNormalBatch(f64, init.gpa, 4);
    defer init.gpa.free(standard_normal_batch);
    const standard_exponential_batch = try rng.standardExponentialBatch(f64, init.gpa, 4);
    defer init.gpa.free(standard_exponential_batch);
    const normal_batch = try rng.normalBatch(f64, init.gpa, 4, 10, 2.5);
    defer init.gpa.free(normal_batch);
    const exponential_batch = try rng.exponentialBatch(f64, init.gpa, 4, 4);
    defer init.gpa.free(exponential_batch);
    const vector_standard_normal_batch = try rng.vectorStandardNormalBatch(@Vector(4, f64), init.gpa, 2);
    defer init.gpa.free(vector_standard_normal_batch);
    const vector_standard_exponential_batch = try rng.vectorStandardExponentialBatch(@Vector(4, f64), init.gpa, 2);
    defer init.gpa.free(vector_standard_exponential_batch);
    const vector_normal_batch = try rng.vectorNormalBatch(@Vector(4, f64), init.gpa, 2, 0, 1);
    defer init.gpa.free(vector_normal_batch);
    const vector_exponential_batch = try rng.vectorExponentialBatch(@Vector(4, f64), init.gpa, 2, 2);
    defer init.gpa.free(vector_exponential_batch);

    const dirichlet = try alea.distributions.Dirichlet(f64).init(&.{ 1.0, 2.0, 3.0 });
    var proportions: [3]f64 = undefined;
    dirichlet.sampleInto(rng, &proportions);

    var deck = [_]u8{ 1, 2, 3, 4, 5, 6, 7, 8 };
    const hand = alea.seq.partialShuffle(rng, u8, &deck, 3);
    const colors = [_][]const u8{ "red", "green", "blue", "gold" };
    var mutable_colors = colors;
    const color_index = rng.chooseIndex(colors.len).?;
    const compact_color_index = rng.chooseIndexU32(@intCast(colors.len)).?;
    const color_index_array = rng.chooseIndexArray(4, colors.len).?;
    const compact_color_index_array = try rng.chooseIndexArrayU32Checked(4, @intCast(colors.len));
    const color_indices = try rng.chooseIndexBatch(init.gpa, 4, colors.len);
    defer init.gpa.free(color_indices);
    const compact_color_indices = try rng.chooseIndexU32Batch(init.gpa, 4, @intCast(colors.len));
    defer init.gpa.free(compact_color_indices);
    const color_value_array = rng.chooseValueArray([]const u8, 4, &colors).?;
    const color_values = try rng.chooseBatch([]const u8, init.gpa, 4, &colors);
    defer init.gpa.free(color_values);
    const color_ptr = rng.chooseConstPtr([]const u8, &colors).?;
    const color_ptr_array = rng.chooseConstPtrArray([]const u8, 4, &colors).?;
    const color_ptrs = try rng.chooseConstPtrBatch([]const u8, init.gpa, 4, &colors);
    defer init.gpa.free(color_ptrs);
    const mutable_color_ptr_array = rng.choosePtrArray([]const u8, 4, &mutable_colors).?;
    const mutable_color_ptrs = try rng.choosePtrBatch([]const u8, init.gpa, 4, &mutable_colors);
    defer init.gpa.free(mutable_color_ptrs);
    const die_sampler = try alea.distributions.Uniform(u8).initInclusive(1, 6);
    const sample_roll = rng.sample(u8, die_sampler);
    const owned_rolls = try rng.sampleBatch(u8, init.gpa, die_sampler, 6);
    defer init.gpa.free(owned_rolls);

    const Iter = struct {
        next_value: u8 = 0,
        pub fn next(self: *@This()) ?u8 {
            if (self.next_value == 10) return null;
            const value = self.next_value;
            self.next_value += 1;
            return value;
        }
    };
    var iter = Iter{};
    const stream_choice = alea.seq.chooseIterator(rng, u8, &iter).?;
    var die_iter = rng.sampleIter(u8, die_sampler);
    const die_iter_hint = die_iter.sizeHint();
    const die_iter_roll = die_iter.next().?;

    seed = seed.mix("child-stream");
    var child_engine = alea.FastPrng.init(seed.stream(42).state);
    const child_rng = alea.Rng.init(&child_engine);

    try stdout.print("dice: {any}\n", .{dice});
    try stdout.print("normal(mean=10,stddev=2.5): {d:.4}\n", .{normal});
    try stdout.print("binomial(n=40,p=.25): {}\n", .{outage_count});
    try stdout.print("weighted index: {}\n", .{weighted});
    try stdout.print("token: {s}\n", .{token});
    try stdout.print("unicode scalars: {s}\n", .{unicode});
    try stdout.print("bytesAlloc: {any}\n", .{random_bytes});
    try stdout.print("nextU64 raw: {}, nextU32 raw: {}\n", .{ raw64, raw32 });
    try stdout.print("fillBytes raw: {any}\n", .{raw_fill_bytes});
    try stdout.print("rngReader bytes: {any}\n", .{reader_bytes});
    try stdout.print("StepRng bytes: {any}, constRng next: {}\n", .{ step_bytes, constant_rng_next });
    try stdout.print("randomValue u16: {}\n", .{random_value});
    try stdout.print("valueBatch u16: {any}\n", .{random_words});
    try stdout.print("uintLessThanBatch u16 <1000: {any}\n", .{bounded_words});
    try stdout.print("uintAtMostBatch u16 <=999: {any}\n", .{inclusive_words});
    try stdout.print("randomBool p=.25: {}, randomRatio 3/8: {}\n", .{ random_bool, random_ratio });
    try stdout.print("root sampler helpers: sampleDie={}, sampleFill={any}, sampleBatch={any}\n", .{ root_sample_die, root_sample_dice_fill, root_sample_dice_batch });
    try stdout.print("root choice helpers: choiceIndex={} ({s}), choiceIndexU32={} ({s}), indexFill={any}, indexFillU32={any}, indexArray={any}, indexArrayU32={any}, valueArray=[{s}, {s}, {s}, {s}], choiceBatch=[{s}, {s}, {s}, {s}]\n", .{ root_choice_index, root_colors[root_choice_index], root_choice_index_u32, root_colors[root_choice_index_u32], root_choice_indices, root_choice_indices_u32, root_choice_index_array, root_choice_index_array_u32, root_choice_value_array[0], root_choice_value_array[1], root_choice_value_array[2], root_choice_value_array[3], root_choice_batch[0], root_choice_batch[1], root_choice_batch[2], root_choice_batch[3] });
    try stdout.print("root repeated choice array helpers: values=[{s}, {s}, {s}, {s}], constPtrs=[{s}, {s}, {s}, {s}], mutPtrs=[{s}, {s}, {s}, {s}]\n", .{ root_choice_repeated_value_array[0], root_choice_repeated_value_array[1], root_choice_repeated_value_array[2], root_choice_repeated_value_array[3], root_choice_repeated_ptr_array[0].*, root_choice_repeated_ptr_array[1].*, root_choice_repeated_ptr_array[2].*, root_choice_repeated_ptr_array[3].*, root_choice_repeated_mut_ptr_array[0].*, root_choice_repeated_mut_ptr_array[1].*, root_choice_repeated_mut_ptr_array[2].*, root_choice_repeated_mut_ptr_array[3].* });
    try stdout.print("root pointer choice helpers: ptr={s}, ptrArray=[{s}, {s}, {s}, {s}], ptrBatch=[{s}, {s}, {s}, {s}]\n", .{ root_choice_ptr.*, root_choice_ptr_array[0].*, root_choice_ptr_array[1].*, root_choice_ptr_array[2].*, root_choice_ptr_array[3].*, root_choice_ptr_batch[0].*, root_choice_ptr_batch[1].*, root_choice_ptr_batch[2].*, root_choice_ptr_batch[3].* });
    try stdout.print("root mutable pointer choice helpers: ptr={s}, ptrArray=[{s}, {s}, {s}, {s}], ptrBatch=[{s}, {s}, {s}, {s}]\n", .{ root_choice_mut_ptr.*, root_choice_mut_ptr_array[0].*, root_choice_mut_ptr_array[1].*, root_choice_mut_ptr_array[2].*, root_choice_mut_ptr_array[3].*, root_choice_mut_ptr_batch[0].*, root_choice_mut_ptr_batch[1].*, root_choice_mut_ptr_batch[2].*, root_choice_mut_ptr_batch[3].* });
    try stdout.print("root shuffle helpers: shuffle={any}, partial={any}, tailPartial={any}\n", .{ root_shuffle_deck, root_partial_hand, root_tail_hand });
    try stdout.print("root no-replacement helpers: sample={any}, sampleArray={any}, chooseArray={any}, samplePtrArray=[{}, {}, {}], samplePtrs=[{}, {}, {}], sampleMutPtrArray=[{}, {}, {}], sampleMutPtrs=[{}, {}, {}], sampleItemsInto={any}, samplePtrsInto=[{}, {}, {}], sampleMutPtrsInto=[{}, {}, {}], indices={any}, indexVec={any}, indexArray={any}, indexArrayU32={any}, indicesInto={any}, indicesU32={any}\n", .{ root_no_replacement, root_no_replacement_array, root_no_replacement_choose_array, root_no_replacement_ptr_array[0].*, root_no_replacement_ptr_array[1].*, root_no_replacement_ptr_array[2].*, root_no_replacement_ptrs[0].*, root_no_replacement_ptrs[1].*, root_no_replacement_ptrs[2].*, root_no_replacement_mut_ptr_array[0].*, root_no_replacement_mut_ptr_array[1].*, root_no_replacement_mut_ptr_array[2].*, root_no_replacement_mut_ptrs[0].*, root_no_replacement_mut_ptrs[1].*, root_no_replacement_mut_ptrs[2].*, root_no_replacement_items_into, root_no_replacement_ptrs_into[0].*, root_no_replacement_ptrs_into[1].*, root_no_replacement_ptrs_into[2].*, root_no_replacement_mut_ptrs_into[0].*, root_no_replacement_mut_ptrs_into[1].*, root_no_replacement_mut_ptrs_into[2].*, root_sample_indices, root_sample_index_vec_values, root_sample_index_array, root_sample_index_array_u32, root_sample_indices_into, root_sample_indices_u32 });
    try stdout.print("root chooseMultiple aliases: chooseMultiple={any}, chooseMultiplePtrs=[{}, {}, {}], chooseMultipleMutPtrs=[{}, {}, {}], chooseMultipleInto={any}, chooseMultiplePtrsInto=[{}, {}, {}], chooseMultipleMutPtrsInto=[{}, {}, {}]\n", .{ root_choose_multiple, root_choose_multiple_ptrs[0].*, root_choose_multiple_ptrs[1].*, root_choose_multiple_ptrs[2].*, root_choose_multiple_mut_ptrs[0].*, root_choose_multiple_mut_ptrs[1].*, root_choose_multiple_mut_ptrs[2].*, root_choose_multiple_into, root_choose_multiple_ptrs_into[0].*, root_choose_multiple_ptrs_into[1].*, root_choose_multiple_ptrs_into[2].*, root_choose_multiple_mut_ptrs_into[0].*, root_choose_multiple_mut_ptrs_into[1].*, root_choose_multiple_mut_ptrs_into[2].* });
    try stdout.print("root sampled iterator helpers: sampleItemsIter={any}, samplePtrsIter=[{}, {}, {}], sampleMutPtrsIter=[{}, {}, {}]\n", .{ root_sample_items_iter_values, root_sample_ptrs_iter_values[0].*, root_sample_ptrs_iter_values[1].*, root_sample_ptrs_iter_values[2].*, root_sample_mut_ptrs_iter_values[0].*, root_sample_mut_ptrs_iter_values[1].*, root_sample_mut_ptrs_iter_values[2].* });
    try stdout.print("root reservoir helpers: reservoirSample={any}, reservoirPtrs=[{}, {}, {}], reservoirMutPtrs=[{}, {}, {}], reservoirInto={any}, reservoirPtrsInto=[{}, {}, {}], reservoirMutPtrsInto=[{}, {}, {}]\n", .{ root_reservoir, root_reservoir_ptrs[0].*, root_reservoir_ptrs[1].*, root_reservoir_ptrs[2].*, root_reservoir_mut_ptrs[0].*, root_reservoir_mut_ptrs[1].*, root_reservoir_mut_ptrs[2].*, root_reservoir_into, root_reservoir_ptrs_into[0].*, root_reservoir_ptrs_into[1].*, root_reservoir_ptrs_into[2].*, root_reservoir_mut_ptrs_into[0].*, root_reservoir_mut_ptrs_into[1].*, root_reservoir_mut_ptrs_into[2].* });
    try stdout.print("root weighted no-replacement helpers: weightedIndices={any}, weightedIndexVec={any}, weightedIndexArray={any}, weightedIndexArrayU32={any}, weightedIndicesInto={any}, weightedIndicesU32Into={any}, weightedValues=[{s}, {s}], weightedValuesInto=[{s}, {s}], weightedArray=[{s}, {s}], weightedPtrs=[{s}, {s}], weightedPtrsInto=[{s}, {s}], weightedMutPtrs=[{s}, {s}], weightedMutPtrsInto=[{s}, {s}]\n", .{ root_sample_weighted_indices, root_sample_weighted_index_vec_values, root_sample_weighted_index_array, root_sample_weighted_index_array_u32, root_sample_weighted_indices_into, root_sample_weighted_indices_u32_into, root_sample_weighted_values[0], root_sample_weighted_values[1], root_sample_weighted_values_into[0], root_sample_weighted_values_into[1], root_sample_weighted_value_array[0], root_sample_weighted_value_array[1], root_sample_weighted_ptrs[0].*, root_sample_weighted_ptrs[1].*, root_sample_weighted_ptrs_into[0].*, root_sample_weighted_ptrs_into[1].*, root_sample_weighted_mut_ptrs[0].*, root_sample_weighted_mut_ptrs[1].*, root_sample_weighted_mut_ptrs_into[0].*, root_sample_weighted_mut_ptrs_into[1].* });
    try stdout.print("root iterator helpers: choice={}, weightedChoice={}, sample={any}, sampleInto={any}, sampleFill={any}, sampleArray={any}, weightedSample={any}, weightedInto={any}, weightedArray={any}\n", .{ root_iterator_choice, root_weighted_iterator_choice, root_iterator_sample, root_iterator_sample_into, root_iterator_sample_fill, root_iterator_sample_array, root_weighted_iterator_sample, root_weighted_iterator_sample_into, root_weighted_iterator_sample_array });
    try stdout.print("root weighted helpers: weightedIndex={}, weightedIndexU32={}, byIndex={}, byIndexU32={}, fillByIndex={any}, fillU32ByIndex={any}, fill={any}, fillU32={any}, array={any}, arrayU32={any}, batch={any}, batchU32={any}\n", .{ root_weighted_index, root_weighted_index_u32, root_weighted_index_by_index, root_weighted_index_u32_by_index, root_weighted_indices_by_index, root_weighted_indices_u32_by_index, root_weighted_indices, root_weighted_indices_u32, root_weighted_index_array, root_weighted_index_u32_array, root_weighted_index_batch, root_weighted_index_u32_batch });
    try stdout.print("root weighted value helpers: value={s}, fill=[{?s}, {?s}, {?s}, {?s}], array=[{s}, {s}, {s}, {s}], batch=[{?s}, {?s}, {?s}, {?s}]\n", .{ root_weighted_value, root_weighted_values[0], root_weighted_values[1], root_weighted_values[2], root_weighted_values[3], root_weighted_value_array[0], root_weighted_value_array[1], root_weighted_value_array[2], root_weighted_value_array[3], root_weighted_value_batch[0], root_weighted_value_batch[1], root_weighted_value_batch[2], root_weighted_value_batch[3] });
    try stdout.print("root weighted pointer helpers: ptr={s}, ptrArray=[{s}, {s}, {s}, {s}], ptrBatch=[{s}, {s}, {s}, {s}]\n", .{ root_weighted_ptr.*, root_weighted_ptr_array_checked[0].*, root_weighted_ptr_array_checked[1].*, root_weighted_ptr_array_checked[2].*, root_weighted_ptr_array_checked[3].*, root_weighted_ptr_batch_checked[0].*, root_weighted_ptr_batch_checked[1].*, root_weighted_ptr_batch_checked[2].*, root_weighted_ptr_batch_checked[3].* });
    try stdout.print("root weighted mutable pointer helpers: ptr={s}, ptrArray=[{s}, {s}, {s}, {s}], ptrBatch=[{s}, {s}, {s}, {s}]\n", .{ root_weighted_mut_ptr.*, root_weighted_mut_ptr_array_checked[0].*, root_weighted_mut_ptr_array_checked[1].*, root_weighted_mut_ptr_array_checked[2].*, root_weighted_mut_ptr_array_checked[3].*, root_weighted_mut_ptr_batch_checked[0].*, root_weighted_mut_ptr_batch_checked[1].*, root_weighted_mut_ptr_batch_checked[2].*, root_weighted_mut_ptr_batch_checked[3].* });
    try stdout.print("root random helpers: random={}, range={}, bool={}, fill={any}, rangeFill={any}, inclusiveFill={any}, boolFill={any}, ratioFill={any}, valueBatch={any}, rangeBatch={any}, boolBatch={any}, ratioBatch={any}, iterNext={}, iterUnbounded={}\n", .{ root_random_value, root_random_range, root_random_bool, root_random_bytes, root_random_range_values, root_random_inclusive_values, root_random_bools, root_random_ratios, root_random_value_batch, root_random_range_batch, root_random_bool_batch, root_random_ratio_batch, root_random_iter_next, root_random_iter_hint.upper == null });
    try stdout.print("root endpoint float helpers: openFill={any}, openBatch={any}, openClosedFill={any}, openClosedBatch={any}\n", .{ root_open_values, root_open_batch, root_open_closed_values, root_open_closed_batch });
    try stdout.print("root duration helpers: lessThan={}ns, atMost={}ns, lessThanBatch={any}, atMostBatch={any}\n", .{ root_duration_less_than.nanoseconds, root_duration_at_most.nanoseconds, root_duration_less_than_batch, root_duration_at_most_batch });
    try stdout.print("root string helpers: char={c}, string={s}, sampleString={s}, appendString={s}, unicodeScalar=U+{X}, unicodeScalarFill={any}, unicodeScalarBatch={any}, unicodeInto={s}, unicodeAlloc={s}\n", .{ root_char, root_string, root_sample_string, root_append_buffer.items, root_unicode_scalar, root_unicode_scalar_fill, root_unicode_scalar_batch, root_unicode_into, root_unicode_alloc });
    try stdout.print("chanceBatch p=.25: {any}\n", .{chance_flags});
    try stdout.print("ratioBatch 3/8: {any}\n", .{ratio_flags});
    try stdout.print("vectorChanceBatch boolx8 p=.25: {any}\n", .{vector_chance_flags});
    try stdout.print("vectorRatioBatch boolx8 3/8: {any}\n", .{vector_ratio_flags});
    try stdout.print("standardNormalBatch: {any}\n", .{standard_normal_batch});
    try stdout.print("standardExponentialBatch: {any}\n", .{standard_exponential_batch});
    try stdout.print("normalBatch: {any}\n", .{normal_batch});
    try stdout.print("exponentialBatch: {any}\n", .{exponential_batch});
    try stdout.print("vectorStandardNormalBatch f64x4: {any}\n", .{vector_standard_normal_batch});
    try stdout.print("vectorStandardExponentialBatch f64x4: {any}\n", .{vector_standard_exponential_batch});
    try stdout.print("vectorNormalBatch f64x4: {any}\n", .{vector_normal_batch});
    try stdout.print("vectorExponentialBatch f64x4: {any}\n", .{vector_exponential_batch});
    try stdout.print("dirichlet: {any}\n", .{proportions});
    try stdout.print("partial shuffle hand: {any}\n", .{hand});
    try stdout.print("index choice: {} ({s})\n", .{ color_index, colors[color_index] });
    try stdout.print("u32 index choice: {} ({s})\n", .{ compact_color_index, colors[compact_color_index] });
    try stdout.print("index choice array: {any}\n", .{color_index_array});
    try stdout.print("u32 index choice array: {any}\n", .{compact_color_index_array});
    try stdout.print("index choice batch: {any}\n", .{color_indices});
    try stdout.print("u32 index choice batch: {any}\n", .{compact_color_indices});
    try stdout.print("value choice array: {s}, {s}, {s}, {s}\n", .{ color_value_array[0], color_value_array[1], color_value_array[2], color_value_array[3] });
    try stdout.print("value choice batch: {s}, {s}, {s}, {s}\n", .{ color_values[0], color_values[1], color_values[2], color_values[3] });
    try stdout.print("const pointer choice: {s}\n", .{color_ptr.*});
    try stdout.print("const pointer choice array: {s}, {s}, {s}, {s}\n", .{ color_ptr_array[0].*, color_ptr_array[1].*, color_ptr_array[2].*, color_ptr_array[3].* });
    try stdout.print("const pointer choice batch: {s}, {s}, {s}, {s}\n", .{ color_ptrs[0].*, color_ptrs[1].*, color_ptrs[2].*, color_ptrs[3].* });
    try stdout.print("mutable pointer choice array: {s}, {s}, {s}, {s}\n", .{ mutable_color_ptr_array[0].*, mutable_color_ptr_array[1].*, mutable_color_ptr_array[2].*, mutable_color_ptr_array[3].* });
    try stdout.print("mutable pointer choice batch: {s}, {s}, {s}, {s}\n", .{ mutable_color_ptrs[0].*, mutable_color_ptrs[1].*, mutable_color_ptrs[2].*, mutable_color_ptrs[3].* });
    try stdout.print("sample die: {}\n", .{sample_roll});
    try stdout.print("sampleBatch dice: {any}\n", .{owned_rolls});
    try stdout.print("iterator choice: {}\n", .{stream_choice});
    try stdout.print("sampleIter sizeHint: {}..unbounded={}, next={}\n", .{ die_iter_hint.lower, die_iter_hint.upper == null, die_iter_roll });
    try stdout.print("child stream u64: {}\n", .{child_rng.next()});
    try stdout.flush();
}
